package com.aiagent.platform.service;

import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class AiAgentService {
    private final GeminiCompletionService geminiCompletionService;

    public AiAgentService(GeminiCompletionService geminiCompletionService) {
        this.geminiCompletionService = geminiCompletionService;
    }

    public String generateEmailDraft() {
        return "Subject: Welcome\n\nHi there,\n\nThis is a demo email draft generated by the AI agent platform.";
    }

    public String generateEmailFromPrompt(String subject, String topic, String tone) {
        String prompt = "Draft a " + tone + " email about " + topic + ". Include a clear subject line and polished body text. Keep the tone " + tone + " and make it professional.";
        if (subject != null && !subject.isBlank()) {
            prompt = "Draft a " + tone + " email with subject: " + subject + ". The topic is " + topic + ". Keep the tone " + tone + " and make it professional.";
        }
        return geminiCompletionService.getCompletion(prompt);
    }

    public String summarizeText(String text, String summaryType) {
        String lengthInstruction = "in 3-4 concise sentences";
        if (!"short".equalsIgnoreCase(summaryType)) {
            lengthInstruction = "in a detailed paragraph covering all key points";
        }
        String prompt = "Summarize the following text " + lengthInstruction + ":\n\n" + text;
        return geminiCompletionService.getCompletion(prompt);
    }

    public String generatePlan(String goal, String timeframe) {
        String prompt = "Create a clear, actionable task plan for the following goal: " + goal +
                ". The timeframe is " + timeframe + ". List the tasks as a numbered list with brief descriptions.";
        return geminiCompletionService.getCompletion(prompt);
    }

    public String translateText(String text, String targetLanguage) {
        String prompt = "Translate the following text into " + targetLanguage + ". Only return the translated text, nothing else:\n\n" + text;
        return geminiCompletionService.getCompletion(prompt);
    }

    public List<Map<String, String>> planTasks() {
        return List.of(
                Map.of("task", "Review project requirements", "status", "Pending"),
                Map.of("task", "Prepare implementation plan", "status", "In Progress")
        );
    }
}