package com.aiagent.platform.service;

import com.aiagent.platform.model.ActivityLog;
import com.aiagent.platform.repository.ActivityLogRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Service
public class AiAgentService {
    private final GeminiCompletionService geminiCompletionService;
    private final ActivityLogRepository activityLogRepository;

    public AiAgentService(GeminiCompletionService geminiCompletionService, ActivityLogRepository activityLogRepository) {
        this.geminiCompletionService = geminiCompletionService;
        this.activityLogRepository = activityLogRepository;
    }

    private void logActivity(String type) {
        activityLogRepository.save(new ActivityLog(type, LocalDateTime.now()));
    }

    public String generateEmailDraft() {
        return "Subject: Welcome\n\nHi there,\n\nThis is a demo email draft generated by the AI agent platform.";
    }

    public String generateEmailFromPrompt(String subject, String topic, String tone) {
        String prompt = "Draft a " + tone + " email about " + topic + ". Include a clear subject line and polished body text. Keep the tone " + tone + " and make it professional.";
        if (subject != null && !subject.isBlank()) {
            prompt = "Draft a " + tone + " email with subject: " + subject + ". The topic is " + topic + ". Keep the tone " + tone + " and make it professional.";
        }
        String result = geminiCompletionService.getCompletion(prompt);
        logActivity("EMAIL");
        return result;
    }

    public String summarizeText(String text, String summaryType) {
        String lengthInstruction = "in 3-4 concise sentences";
        if (!"short".equalsIgnoreCase(summaryType)) {
            lengthInstruction = "in a detailed paragraph covering all key points";
        }
        String prompt = "Summarize the following text " + lengthInstruction + ":\n\n" + text;
        String result = geminiCompletionService.getCompletion(prompt);
        logActivity("PDF");
        return result;
    }

    public String generatePlan(String goal, String timeframe) {
        String prompt = "Create a clear, actionable task plan for the following goal: " + goal +
                ". The timeframe is " + timeframe + ". List the tasks as a numbered list with brief descriptions.";
        String result = geminiCompletionService.getCompletion(prompt);
        logActivity("PLANNER");
        return result;
    }

    public String translateText(String text, String targetLanguage) {
        String prompt = "Translate the following text into " + targetLanguage + ". Only return the translated text, nothing else:\n\n" + text;
        String result = geminiCompletionService.getCompletion(prompt);
        logActivity("TRANSLATOR");
        return result;
    }

    public String chatWithLogging(String message) {
        String result = geminiCompletionService.getCompletion(message);
        logActivity("CHAT");
        return result;
    }

    public Map<String, Long> getStats() {
        return Map.of(
                "chat", activityLogRepository.countByType("CHAT"),
                "email", activityLogRepository.countByType("EMAIL"),
                "pdf", activityLogRepository.countByType("PDF"),
                "planner", activityLogRepository.countByType("PLANNER"),
                "translator", activityLogRepository.countByType("TRANSLATOR")
        );
    }

    public List<Map<String, String>> planTasks() {
        return List.of(
                Map.of("task", "Review project requirements", "status", "Pending"),
                Map.of("task", "Prepare implementation plan", "status", "In Progress")
        );
    }
}